# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

# Version
mod_version=11.0.2
artifact_type=release

# Minecraft
minecraft_version=1.21.11
minecraft_version_range=[1.21.11]

# NeoForge
neo_version=21.11.25-beta
neo_version_range=[21.11.25-beta,)
loader_version_range=[10,)

# Mappings
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20

# Mod Properties
mod_name=Useless Mod
mod_id=uselessmod
mod_group_id=net.themcbrothers
mod_authors=TheMCLoveMan
mod_credits=Thank you for every single download!
mod_description=A mod for Minecraft. Not very useless!
mod_license=MIT License
catalogue_item_icon=uselessmod:useless_ingot

# Dependencies
lib_version=9.0.0
lib_version_range=[1.21.11-9.0.0,)
jei_version=27.4.0.15

# Publishing
supported_game_versions=1.21.2
maven_name=useless-mod
github_repo=TheMCBrothers/Useless-Mod
curse_project_id=322455
modrinth_project_id=yDQBgtWH
