@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.uselessmod.compat.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;