modLoader = "javafml"
loaderVersion = "${loaderVersionRange}"
license = "${modLicense}"
issueTrackerURL = "${modIssues}"

[[mods]]
    modId = "${modId}"
    version = "${file.jarVersion}"
    displayName = "${modName}"
    updateJSONURL = "${modUpdateJSON}"
    displayURL = "${modURL}"
    logoFile = "logo.png"
    logoBlur = false
    credits = "${modCredits}"
    authors = "${modAuthors}"
    description = "${modDescription}"

[[dependencies.${modId}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forgeVersionRange}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraftVersionRange}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "tmcb_lib"
    mandatory = true
    versionRange = "${libraryVersionRange}"
    ordering = "NONE"
    side = "BOTH"

[modproperties.${modId}]
    catalogueItemIcon="${catalogueItemIcon}"
    catalogueImageIcon="icon.png"
    configuredBackground = "${configuredBackground}"
