modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (30 is current forge version)
issueTrackerURL="https://minecraft.curseforge.com/projects/themcbros-useless-mod/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
    modId="uselessmod"
    version="${file.jarVersion}"
    displayName="Useless Mod"
    updateJSONURL="https://raw.githubusercontent.com/TheMCBrothers/UselessMod/master/update.json" #optional
    displayURL="http://uselessmod.tk" #optional
    logoFile="useless_logo.png" #optional
    credits="Thanks for over 28000 downloads!" #optional
    authors="TheMCLoveMan (Code) & TheMCCrazyMan (Textures)" #optional
    description='''
    This ia a not really useless mod for minecraft 1.15.2. Enjoy this mod with technology and other things!
    '''

[[dependencies.uselessmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.uselessmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.uselessmod]]
    modId="filters"
    mandatory=false
    versionRange="[1.1.1,)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.uselessmod]]
    modId="ironjetpacks"
    mandatory=false
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.uselessmod]]
    modId="mysticalagriculture"
    mandatory=false
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"