modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT License"
issueTrackerURL = "https://github.com/TheMCBrothers/Useless-Mod/issues"

[[mods]]
    modId = "uselessmod"
    version = "${file.jarVersion}"
    displayName = "Useless Mod"
    updateJSONURL = "https://raw.githubusercontent.com/TheMCBrothers-Manager/Version/master/uselessmod_update.json"
    displayURL = "https://themcbrothers.net/mods/uselessmod"
    logoFile = "uselessmod.png"
    credits = "Thank you for every single download!"
    authors = "TheMCBrothers"
    description = "A mod for Minecraft. Not very useless ;)"

[[dependencies.uselessmod]]
    modId = "forge" #mandatory
    mandatory = true #mandatory
    versionRange = "[39.2,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering = "NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side = "BOTH"

[[dependencies.uselessmod]]
    modId = "minecraft"
    mandatory = true
    versionRange = "1.18.2"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.uselessmod]]
    modId = "tmcb_lib"
    mandatory = true
    versionRange = "[1.18.2-2.0.4,)"
    ordering = "NONE"
    side = "BOTH"

[modproperties.uselessmod]
    catalogueItemIcon = "uselessmod:useless_ingot"
    configuredBackground = "uselessmod:textures/block/useless_planks.png"
