modLoader = "javafml"
loaderVersion = "${project.loader_version_range}"
license = "${project.mod_license}"
issueTrackerURL = "https://github.com/${project.github_repo}/issues"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[mods]]
    modId = "${project.mod_id}"
    version = "${project.version}"
    displayName = "${project.mod_name}"
    updateJSONURL = "https://neoforge.curseupdate.com/${project.curse_project_id}/${project.mod_id}"
    displayURL = "https://themcbrothers.net/mods"
    logoFile = "logo.png"
    logoBlur = false
    authors = "${project.mod_authors}"
    credits = "${project.mod_credits}"
    description = '''${project.mod_description}'''

[[dependencies.${project.mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${project.neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${project.mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${project.minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${project.mod_id}]]
    modId = "tmcb_lib"
    type = "required"
    versionRange = "${project.lib_version_range}"
    ordering = "NONE"
    side = "BOTH"

[modproperties.${project.mod_id}]
    catalogueItemIcon = "${project.catalogue_item_icon}"
    catalogueImageIcon = "icon.png"
