@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.uselessmod.init;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;