@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tk.themcbros.uselessmod.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;