@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.uselessmod.client.models.block.wall_closet;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;