@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package themcbros.uselessmod.client.renderer.entity.layer;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;