@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.uselessmod.world.structure;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;