@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package themcbros.uselessmod.client.renderer.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;