@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.themcbrothers.uselessmod.datagen.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;